### ISSUE TITLE
Include rental_url in rentals

### ISSUE THREAD

**Issue by bkniffler** [BookingSync/bookingsync-api-docs#340]
I found that rentals can't be fetched with rental_url included, but rental_urls can be fetched with the rentals. Wouldn't it make sense to include rental_url into the /rentals endpoint?

**Comment by Azdaroth** [comment]
@bkniffler You mean you would like to sideload rental_urls relationship when fetching rentals? In general, that's not a recommended approach and that's why at some point new associations were stopped from getting added. Sideloading is ok when you have a strict transaction boundary (e.g. booking + bookings taxes + bookings fees in a context of anything related to price as it might be a problem when using booking's final price if the sum of all its components doesn't match). Otherwise, the recommended approach is to fetch resources separately using update since flow as described here: http://developers.bookingsync.com/guides/updated-since-flow/

**Comment by bkniffler** [comment]
Makes sense. So your recommendation is to fetch all rentals and all rental_urls separately, keep them updated with updated-since flow and make the appropriate associations in our own systems.
